version: "3.9"
services:	
    
    iperf-server:
      build: server
      networks:
          - iperf

      ports:
        - 5201:5201
    iperf-client:
      build: client
      networks:
        - iperf
      depends_on:
        - iperf-server

networks:
  iperf:
    driver: host
